CREATE TABLE IF NOT EXISTS "TRANSACTIONS" (
    "TRANSACTION_ID" INTEGER NOT NULL,
    "TITLE" TEXT NOT NULL DEFAULT 'No_Title',
    "AMOUNT" NUMERIC NOT NULL CHECK("AMOUNT" != 0),
    "TYPE" TEXT NOT NULL CHECK("TYPE" IN ('Expense', 'Income')),
    "DATETIME" NUMERIC NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY("TRANSACTION_ID")
);